/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ControllerMusicaDialog;
import model.Musica;

/**
 *
 * @author Guilherme Rocha
 */
public class MusicaDialog extends javax.swing.JDialog {
    private ControllerMusicaDialog c;
    private Musica musica;
    
    public MusicaDialog(java.awt.Frame parent, boolean modal, Musica musica) {
        //Inicializando variáveus
        super(parent, modal);
        this.musica = musica;
        c = new ControllerMusicaDialog(this);
        initComponents();
        //Inicializando textos no frame correspondente a musica clicada
        lbl_musica.setText(musica.getTitulo());
        lbl_artista.setText("Por " + musica.getArtista().getNome());
        lbl_avaliacao.setText("Avaliação do usuário: " + c.verificarAvaliacaoDeMusica(musica));
        //Centralizando Tela
        this.setLocationRelativeTo(null);      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_musica = new javax.swing.JLabel();
        bt_curtir = new javax.swing.JButton();
        bt_descurtir = new javax.swing.JButton();
        lbl_artista = new javax.swing.JLabel();
        lbl_avaliacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_musica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_musica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_musica.setText("Nome da Musica");

        bt_curtir.setText("Curtir");
        bt_curtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_curtirActionPerformed(evt);
            }
        });

        bt_descurtir.setText("Descurtir");
        bt_descurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_descurtirActionPerformed(evt);
            }
        });

        lbl_artista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_artista.setText("por nome do artista");

        lbl_avaliacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_avaliacao.setText("Avaliação do usuário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_avaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)))
                            .addGap(75, 75, 75))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(bt_curtir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bt_descurtir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(61, 61, 61)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_musica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_artista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_avaliacao)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_curtir)
                    .addComponent(bt_descurtir))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bt_curtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_curtirActionPerformed
       /*A variável avaliacaoFinal guarda a string que representa o estado final da avaliação da musica
          apos o usuario cliacar em curtir ou descurtir*/
        String avaliacaoFinal = c.avaliarMusica(musica, "curtida", lbl_avaliacao.getText().substring(22));  
        lbl_avaliacao.setText("Avaliação do usuário: " + avaliacaoFinal);
    }//GEN-LAST:event_bt_curtirActionPerformed

    private void bt_descurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_descurtirActionPerformed
        /*A variável avaliacaoFinal guarda a string que representa o estado final da avaliação da musica
          apos o usuario cliacar em curtir ou descurtir*/
        String avaliacaoFinal = c.avaliarMusica(musica, "descurtida", lbl_avaliacao.getText().substring(22));
        lbl_avaliacao.setText("Avaliação do usuário: " + avaliacaoFinal);
    }//GEN-LAST:event_bt_descurtirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_curtir;
    private javax.swing.JButton bt_descurtir;
    private javax.swing.JLabel lbl_artista;
    private javax.swing.JLabel lbl_avaliacao;
    private javax.swing.JLabel lbl_musica;
    // End of variables declaration//GEN-END:variables
}
