/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ControllerPlaylistCriacaoDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Guilherme Rocha
 */
public class PlaylistCriacaoDialog extends javax.swing.JDialog {
    private ControllerPlaylistCriacaoDialog c;
    private boolean sucesso;

    public PlaylistCriacaoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        c = new ControllerPlaylistCriacaoDialog(this);
        boolean sucesso = false;
        //Centralizando Tela
        this.setLocationRelativeTo(null);  
    }

    public boolean isSucesso() {
        return sucesso;
    }

    public void setSucesso(boolean sucesso) {
        this.sucesso = sucesso;
    }
    
    public JTextField getTxt_playlist_nome() {
        return txt_playlist_nome;
    }

    public void setTxt_playlist_nome(JTextField txt_playlist_nome) {
        this.txt_playlist_nome = txt_playlist_nome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_playlist_nome = new javax.swing.JLabel();
        txt_playlist_nome = new javax.swing.JTextField();
        bt_continuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_playlist_nome.setText("Nome da Playlist:");

        bt_continuar.setText("CONTINUAR");
        bt_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_continuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbl_playlist_nome)
                        .addGap(18, 18, 18)
                        .addComponent(txt_playlist_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(bt_continuar)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_playlist_nome)
                    .addComponent(txt_playlist_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(bt_continuar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_continuarActionPerformed
        if (txt_playlist_nome.getText() == null || txt_playlist_nome.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nome não pode ser vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        sucesso = false;
        sucesso = c.criarPlaylist(txt_playlist_nome.getText());
        if(sucesso){
            dispose();
        }    
    }//GEN-LAST:event_bt_continuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_continuar;
    private javax.swing.JLabel lbl_playlist_nome;
    private javax.swing.JTextField txt_playlist_nome;
    // End of variables declaration//GEN-END:variables
}
