/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerPrincipalHome;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumnModel;
import model.Musica;

/**
 *
 * @author Guilherme Rocha
 */
public class PrincipalFrame extends javax.swing.JFrame {
    private ControllerPrincipalHome c;
    
    public PrincipalFrame() {
        initComponents();
        //Centralizando Tela
        this.setLocationRelativeTo(null);
        c = new ControllerPrincipalHome(this);
        //Escondendo a coluna id da tabela de busca de musicas
        TableColumnModel tcm = home_tb_busca.getColumnModel();
        tcm.removeColumn(tcm.getColumn(5));  
    }

    public JTable getHome_tb_busca() {
        return home_tb_busca;
    }

    public void setHome_tb_busca(JTable tb_busca) {
        this.home_tb_busca = tb_busca;
    }

    public JRadioButton getHome_rb_busca_artista() {
        return home_rb_busca_artista;
    }

    public void setHome_rb_busca_artista(JRadioButton rb_busca_artista) {
        this.home_rb_busca_artista = rb_busca_artista;
    }

    public JRadioButton getHome_rb_busca_genero() {
        return home_rb_busca_genero;
    }

    public void setHome_rb_busca_genero(JRadioButton rb_busca_genero) {
        this.home_rb_busca_genero = rb_busca_genero;
    }

    public JRadioButton getHome_rb_busca_titulo() {
        return home_rb_busca_titulo;
    }

    public void setHome_rb_busca_titulo(JRadioButton rb_busca_titulo) {
        this.home_rb_busca_titulo = rb_busca_titulo;
    }

    public JTextField getHome_txt_busca() {
        return home_txt_busca;
    }

    public void setHome_txt_busca(JTextField txt_busca) {
        this.home_txt_busca = txt_busca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_rbg_busca = new javax.swing.ButtonGroup();
        tp_principal = new javax.swing.JTabbedPane();
        panel_home = new javax.swing.JPanel();
        home_txt_busca = new javax.swing.JTextField();
        home_lbl_filtro = new javax.swing.JLabel();
        home_rb_busca_titulo = new javax.swing.JRadioButton();
        home_rb_busca_artista = new javax.swing.JRadioButton();
        home_rb_busca_genero = new javax.swing.JRadioButton();
        home_bt_busca = new javax.swing.JButton();
        home_sp_busca = new javax.swing.JScrollPane();
        home_tb_busca = new javax.swing.JTable();
        panel_playlist = new javax.swing.JPanel();
        panel_historico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        home_txt_busca.setText("Procurar Música");
        home_txt_busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                home_txt_buscaFocusGained(evt);
            }
        });

        home_lbl_filtro.setText("Procurar por:");

        home_rbg_busca.add(home_rb_busca_titulo);
        home_rb_busca_titulo.setText("Titulo");

        home_rbg_busca.add(home_rb_busca_artista);
        home_rb_busca_artista.setText("Artista");

        home_rbg_busca.add(home_rb_busca_genero);
        home_rb_busca_genero.setText("Gênero");

        home_bt_busca.setText("P");
        home_bt_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_bt_buscaActionPerformed(evt);
            }
        });

        home_tb_busca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Duração", "Gênero", "Lançamento", "Artista", "Musica_Object_Invisivel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        home_tb_busca.getTableHeader().setReorderingAllowed(false);
        home_tb_busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_tb_buscaMouseClicked(evt);
            }
        });
        home_sp_busca.setViewportView(home_tb_busca);
        if (home_tb_busca.getColumnModel().getColumnCount() > 0) {
            home_tb_busca.getColumnModel().getColumn(0).setResizable(false);
            home_tb_busca.getColumnModel().getColumn(1).setResizable(false);
            home_tb_busca.getColumnModel().getColumn(2).setResizable(false);
            home_tb_busca.getColumnModel().getColumn(3).setResizable(false);
            home_tb_busca.getColumnModel().getColumn(4).setResizable(false);
            home_tb_busca.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_homeLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_homeLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(home_txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(home_bt_busca))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_homeLayout.createSequentialGroup()
                                    .addComponent(home_rb_busca_titulo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(home_rb_busca_artista)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(home_rb_busca_genero)))
                            .addGroup(panel_homeLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(home_lbl_filtro))))
                    .addGroup(panel_homeLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(home_sp_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_bt_busca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home_lbl_filtro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_rb_busca_titulo)
                    .addComponent(home_rb_busca_artista)
                    .addComponent(home_rb_busca_genero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(home_sp_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        tp_principal.addTab("Home", panel_home);

        javax.swing.GroupLayout panel_playlistLayout = new javax.swing.GroupLayout(panel_playlist);
        panel_playlist.setLayout(panel_playlistLayout);
        panel_playlistLayout.setHorizontalGroup(
            panel_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        panel_playlistLayout.setVerticalGroup(
            panel_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        tp_principal.addTab("Playlists", panel_playlist);

        javax.swing.GroupLayout panel_historicoLayout = new javax.swing.GroupLayout(panel_historico);
        panel_historico.setLayout(panel_historicoLayout);
        panel_historicoLayout.setHorizontalGroup(
            panel_historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        panel_historicoLayout.setVerticalGroup(
            panel_historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        tp_principal.addTab("Historico", panel_historico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_principal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_bt_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_bt_buscaActionPerformed
        c.buscarMusica();
    }//GEN-LAST:event_home_bt_buscaActionPerformed

    private void home_txt_buscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_home_txt_buscaFocusGained
        if(home_txt_busca.getText().equals("Procurar Música")){
            home_txt_busca.setText("");
        }
    }//GEN-LAST:event_home_txt_buscaFocusGained

    private void home_tb_buscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_tb_buscaMouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );
        Musica musica = (Musica) source.getModel().getValueAt(row, 5);

        //Abrindo MusicaDialog com a musica clicada sendo passada como argumento
        MusicaDialog md = new MusicaDialog(this, true, musica);
        md.setVisible(true);
    }//GEN-LAST:event_home_tb_buscaMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home_bt_busca;
    private javax.swing.JLabel home_lbl_filtro;
    private javax.swing.JRadioButton home_rb_busca_artista;
    private javax.swing.JRadioButton home_rb_busca_genero;
    private javax.swing.JRadioButton home_rb_busca_titulo;
    private javax.swing.ButtonGroup home_rbg_busca;
    private javax.swing.JScrollPane home_sp_busca;
    private javax.swing.JTable home_tb_busca;
    private javax.swing.JTextField home_txt_busca;
    private javax.swing.JPanel panel_historico;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_playlist;
    private javax.swing.JTabbedPane tp_principal;
    // End of variables declaration//GEN-END:variables

}
